import numpy as np
import sys,os
from PIL import Image

#inputfile=str(sys.argv[1])
inputfile='ERR013138.filt.fastq'
idstrlist=[]
basestrlist=[]
qualitystrlist=[]
SEQLINES=0
with open(inputfile,'r') as A1: # input MSA generated by clustal omega
    lines=A1.readlines()
    totalength=len(lines)
    i=0
    while (i<5200):
        A1.readlines()
        i=i+1
    while (i>=5200 and i <6000):
        line=lines[i].strip()
        #if line.startswith('@'):
        #    i=i+1
        idstrlist.append(line)
        i=i+1
        line=lines[i].strip()
        basestrlist.append(line)
        i=i+2
        line=lines[i].strip()
        qualitystrlist.append(line)
        i=i+1
        SEQLINES=SEQLINES+1
A1.close()

imageheight=SEQLINES
#imageheight=4
imagewidth1=len(lines[0].strip())
imagewidth2=len(lines[1].strip())

idarray=[[0 for j in range(imagewidth1)] for i in range(imageheight)]
basearray=[[0 for j in range(imagewidth2)] for i in range(imageheight)]
qualityarray=[[0 for j in range(imagewidth2)] for i in range(imageheight)]
#basedict = {'A':128, 'C':64, 'G':32, 'T':16, 'N':0 }
basedict = {'A':32, 'C':64, 'G':192, 'T':224, 'N':0 }

for i in range(imageheight):
    for j in range(imagewidth1):
        idarray[i][j]=ord(idstrlist[i][j])*2
    for j in range(imagewidth2):
        basearray[i][j]=basedict[basestrlist[i][j]]
        #qualityarray[i][j]=(ord(qualitystrlist[i][j])-ord(qualitystrlist[i][0]))*2
        qualityarray[i][j]=ord(qualitystrlist[i][j])*2
#for i in range(imageheight):
 #   for j in range(imagewidth2):
 #       qualityarray[i][j]=qualityarray[i][j]-qualityarray[0][j]
a=np.array(np.uint8(idarray))
b=np.array(np.uint8(basearray))
c=np.array(np.uint8(qualityarray))
#b=np.array(qualityarray,dtype='unicode')

ima=Image.fromarray(a)
ima.save(r'a_4_1300_1500.tiff')
#imb=Image.frombytes('I',(imagewidth,imageheight),b)
imb=Image.fromarray(b)
imb.save(r'b_4_1300_1500.tiff')
imb=Image.fromarray(c)
imb.save(r'c_4_1300_1500.tiff')